[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_SUPABASE_URL = "https://gfgtabtnjlntsbmylniu.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdmZ3RhYnRuamxudHNibXlsbml1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2Mzc1OTYsImV4cCI6MjA2MDIxMzU5Nn0.cOfHM-QM8pzrCOwUMdgi0Cdee9nW3dz8GqDrN-STCDE"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild" 